version: "2"

services:
  piper:
    build: piper
    restart: always
    ports:
      - 10200:5000
  sebaschtian:
    build:
      context: .
      target: fish
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
    restart: always
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - sound-data:/sound-data
    depends_on:
      - otel-collector
  sound:
    build:
      context: .
      target: sounds
    ports:
      - "80:80"
    restart: always
    privileged: true
    environment:
      SOUNDS_PORT: 80
    volumes:
      - sound-data:/app/sound-data
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/dma_heap:/dev/dma_heap
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
      - /dev/video19:/dev/video19
      - /dev/video20:/dev/video20
      - /dev/video21:/dev/video21
      - /dev/video22:/dev/video22
      - /dev/video23:/dev/video23
      - /dev/video31:/dev/video31
    depends_on:
      - otel-collector

  otel-collector:
    build: otel
    labels:
      io.balena.features.balena-socket: "1"
    pid: host
    privileged: true
    restart: always
    environment:
      - OTEL_REMOTE_ENDPOINT=127.0.0.1:55666
      - OTEL_REMOTE_AUTH_HEADER=
      - OTEL_REMOTE_INSECURE=true
      - GCP_KEY=${GCP_KEY}
    ports:
      - "4317:4317"
      - "4318:4318"

  balena-monitor:
    build:
      context: .
      target: balena-monitor
    restart: always
    labels:
      io.balena.features.supervisor-api: "1"
    depends_on:
      - otel-collector

volumes:
  ollama_data:
  sound-data:
