version: "2"

services:
  ollama:
    ports:
      - 11434:11434
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
  piper:
    build: piper
    ports:
      - 10200:5000
  sebaschtian:
    build:
      context: .
      target: fish
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: '1'
  sounds:
    build:
      context: .
      target: sounds
    ports:
      - "8080:8080"
    volumes:
      - sound-data:/app/sound-data
volumes:
  ollama_data:
  sound-data:
