version: "2"

services:
  piper:
    build: piper
    ports:
      - 10200:5000
  sebaschtian:
    build:
      context: .
      target: fish
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - sound-data:/sound-data
  sound:
    build:
      context: .
      target: sounds
    ports:
      - "80:80"
    environment:
      SOUNDS_PORT: 80
    volumes:
      - sound-data:/app/sound-data
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
volumes:
  ollama_data:
  sound-data:
