version: "2"

services:
  ollama:
    ports:
      - 11434:11434
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
  piper:
    build: piper
    ports:
      - 10200:5000
  sebaschtian:
    build: .
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: '1'
volumes:
  ollama_data:
