receivers:
  otlp:
    protocols:
      grpc:
      http:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      load:
      network:
      disk:
      filesystem:

  docker_stats:
    endpoint: unix:///var/run/balena-engine.sock
    collection_interval: 10s
    timeout: 20s
    api_version: 1.24

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  
  otlp/remote:
    endpoint: "${env:OTEL_REMOTE_ENDPOINT}"
    tls:
      insecure: ${env:OTEL_REMOTE_INSECURE}
    headers:
      "Authorization": "${env:OTEL_REMOTE_AUTH_HEADER}"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats, otlp]
      processors: [batch]
      exporters: [debug, otlp/remote]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/remote]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/remote]
